openapi: 3.0.3
info:
  title: Team tells generated
  version: 1.0.0
paths:
  /authorization/salt/{login}:
    get:
      description: get salt by login
      parameters:
        - name: login
          in: path
          description: login of user
          required: true
          schema:
            type: string
      operationId: GetSaltByLogin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/saltResponse'
        '404':
          description: User not found
  /authorization/login:
    post:
      operationId: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginResponse'
        '404':
          description: User with login and password not found
  /authorization/refresh-token:
    get:
      operationId: RefreshToken
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenResponse'
  /authorization/logout:
    post:
      operationId: Logout
      responses:
        '200':
          description: OK

components:
  schemas:
    saltResponse:
      type: object
      properties:
        salt:
          type: string

    loginRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string

    tokenResponse:
      type: object
      properties:
        accessJwtToken:
          type: string

    loginResponse:
      type: object
      required:
        - accessJwtToken
        - user
        - company
      properties:
        accessJwtToken:
          type: string
        user:
          $ref: '#/components/schemas/user'
        company:
          $ref: '#/components/schemas/company'

    user:
      type: object
      required:
        - id
      properties:
        id:
          format: User
          type: integer

    company:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
